    promtail:
      enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
    pipelineStages:
      - docker: {}
      - drop:
          source: namespace
          expression: "kube-.*"
    prometheus:
      enabled: false
    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    loki:
      enabled: true
    # Configure for 28 day retention on persistent volume
    persistence:
      enabled: true
      size: 10Gi
    config:
      chunk_store_config:
        max_look_back_period: 672h
      table_manager:
        retention_deletes_enabled: true
        retention_period: 672h

